// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import "strconv"

type ExecutorMessage byte

const (
	ExecutorMessageNONE        ExecutorMessage = 0
	ExecutorMessageexec_result ExecutorMessage = 1
	ExecutorMessageexecuting   ExecutorMessage = 2
	ExecutorMessagestats       ExecutorMessage = 3
)

var EnumNamesExecutorMessage = map[ExecutorMessage]string{
	ExecutorMessageNONE:        "NONE",
	ExecutorMessageexec_result: "exec_result",
	ExecutorMessageexecuting:   "executing",
	ExecutorMessagestats:       "stats",
}

var EnumValuesExecutorMessage = map[string]ExecutorMessage{
	"NONE":        ExecutorMessageNONE,
	"exec_result": ExecutorMessageexec_result,
	"executing":   ExecutorMessageexecuting,
	"stats":       ExecutorMessagestats,
}

func (v ExecutorMessage) String() string {
	if s, ok := EnumNamesExecutorMessage[v]; ok {
		return s
	}
	return "ExecutorMessage(" + strconv.FormatInt(int64(v), 10) + ")"
}
