// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import "strconv"

type HostMessage byte

const (
	HostMessageNONE          HostMessage = 0
	HostMessageexec_request  HostMessage = 1
	HostMessagesignal_update HostMessage = 2
)

var EnumNamesHostMessage = map[HostMessage]string{
	HostMessageNONE:          "NONE",
	HostMessageexec_request:  "exec_request",
	HostMessagesignal_update: "signal_update",
}

var EnumValuesHostMessage = map[string]HostMessage{
	"NONE":          HostMessageNONE,
	"exec_request":  HostMessageexec_request,
	"signal_update": HostMessagesignal_update,
}

func (v HostMessage) String() string {
	if s, ok := EnumNamesHostMessage[v]; ok {
		return s
	}
	return "HostMessage(" + strconv.FormatInt(int64(v), 10) + ")"
}
