// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StatsMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsStatsMessage(buf []byte, offset flatbuffers.UOffsetT) *StatsMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StatsMessage{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsStatsMessage(buf []byte, offset flatbuffers.UOffsetT) *StatsMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StatsMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *StatsMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StatsMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StatsMessage) NoexecCount() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatsMessage) MutateNoexecCount(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *StatsMessage) NoexecDuration() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatsMessage) MutateNoexecDuration(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func StatsMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func StatsMessageAddNoexecCount(builder *flatbuffers.Builder, noexecCount int64) {
	builder.PrependInt64Slot(0, noexecCount, 0)
}
func StatsMessageAddNoexecDuration(builder *flatbuffers.Builder, noexecDuration int64) {
	builder.PrependInt64Slot(1, noexecDuration, 0)
}
func StatsMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
