// Copyright 2026 syzkaller project authors. All rights reserved.
// Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

package syzlang

import (
	"encoding/json"
	"errors"

	"github.com/google/syzkaller/pkg/aflow"
	"github.com/google/syzkaller/pkg/aflow/action/crash"
	"github.com/google/syzkaller/prog"
	_ "github.com/google/syzkaller/sys"
)

var Reproduce = aflow.NewFuncTool("reproduce-crash", reproduce, `
Tool evaluates whether the given syz repro program crashes the kernel.
It will compile the program and execute it in a VM.
You MUST use this tool to verify your generated syz repro program.
`)

type reproduceArgs struct {
	ReproSyz string `jsonschema:"Syz program to verify and execute."`
}

type reproduceResult struct {
	ReproducedBugTitle    string `jsonschema:"Bug title triggered by the reproducer."`
	ReproducedCrashReport string `jsonschema:"Crash report generated by the reproducer."`
	CoverageID            string `jsonschema:"Coverage ID. Pass to coverage tools to explore executed code."`
}

type reproduceState struct {
	KernelSrc    string
	KernelCommit string
	KernelConfig string
	KernelObj    string
	Image        string
	Type         string
	VM           json.RawMessage
	Syzkaller    string
	StraceBin string
}

func reproduce(ctx *aflow.Context, state reproduceState, args reproduceArgs) (reproduceResult, error) {
	if args.ReproSyz == "" {
		return ReproduceResult{}, aflow.BadCallError("syz program cannot be empty")
	}

	pt, err := prog.GetTarget("linux", "amd64")
	if err != nil {
		return ReproduceResult{}, err
	}
	_, err = pt.Deserialize([]byte(args.ReproSyz), prog.Strict)
	if err != nil {
		return ReproduceResult{}, aflow.BadCallError("%v", err)
	}

	if state.Image == "" || state.VM == nil {
		// VM configuration is missing, we can only verify the program compiles.
		// This is required for unit tests that pass an empty state.
		return ReproduceResult{}, nil
	}

	reproArgs := crash.ReproduceArgs{
		Syzkaller:    state.Syzkaller,
		Image:        state.Image,
		Type:         state.Type,
		VM:           state.VM,
		KernelSrc:    state.KernelSrc,
		KernelObj:    state.KernelObj,
		KernelCommit: state.KernelCommit,
		KernelConfig: state.KernelConfig,
		StraceBin: state.StraceBin,
		ReproSyz:     args.ReproSyz,
	}

	// TODO: also run under strace and expose results to LLM.
	testRes, coverageID, err := crash.DoReproduce(ctx, reproArgs, true, false)
	if err != nil {
		if errors.Is(err, crash.ErrDidNotCrash) {
			return ReproduceResult{CoverageID: coverageID}, nil
		}
		return ReproduceResult{}, err
	}

	return ReproduceResult{
		ReproducedBugTitle:    testRes.ReproducedBugTitle,
		ReproducedCrashReport: testRes.ReproducedCrashReport,
		CoverageID:            coverageID,
	}, nil
}
